# Generated by Django 3.0.8 on 2020-07-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bid_bid_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
