# Generated by Django 3.0.8 on 2020-07-15 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bid_bid_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='WinnerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.Bid')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('won_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.AuctionListing')),
            ],
        ),
    ]
