# Generated by Django 3.0.8 on 2020-07-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_comment_comment_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='is_bid',
            field=models.BooleanField(default=False),
        ),
    ]
