# Generated by Django 3.0.8 on 2020-07-15 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auctionlisting_is_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='of_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.AuctionListing'),
        ),
    ]
